name: CI/CD Pipeline 

on:
  push:
    branches: [work]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DEBUG: ${{ secrets.DEBUG }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: '*'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python3 manage.py test

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Fetch all branches
        run: |
          git fetch origin

      - name: Checkout work branch
        run: |
          git checkout work

      - name: Merge work into main
        run: |
          git checkout main
          git merge work --no-ff --no-edit

      - name: Push changes to main
        run: |
          git push origin main
